### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by XomaDev** [ShreyashSaitwal/rush-cli#17]
When I try to build the extension created with Rush, this error occurs:

```
user@DESKTOP-BD6HS68 MINGW64 ~/Desktop/SymbolTest/special-chars
$ rush build
                      __
     _______  _______/ /_
    / ___/ / / / ___/ __ \
   / /  / /_/ (__  / / / /
  /_/   \__,_/____/_/ /_/

• Build initialized

┌ Checking project files
│
│  OK Metadata file (rush.yml) found
│
│  OK AndroidManifest.xml file found
└ Done
Unhandled exception:
type 'Null' is not a subtype of type 'DateTime'
#0      BuildCommand.run (package:rush_cli/commands/build_command/build_command.dart:182)
<asynchronous suspension>
#1      CommandRunner.runCommand (package:args/command_runner.dart:196)
<asynchronous suspension>
```

Well, there is just a single project which seems to work. Which was created while before updating the rust to 1.1.0 or the latest version.

**Comment by ShreyashSaitwal** [comment]
Can you try changing something in the `AndroidManifest.xml`? This will update its last-modified DateTime value.

**Comment by XomaDev** [comment]
Yes, I needed to add a service element. I will try changing things.

**Comment by XomaDev** [comment]
Changing anything in the Manifest file doesn't work.

**Comment by ShreyashSaitwal** [comment]
Okay, try replacing rush.exe in the bin directory with the EXE from this ZIP: [rush.zip](https://github.com/ShreyashSaitwal/rush-cli/files/6385088/rush.zip)

**Comment by XomaDev** [comment]
Yes, this works. Ran three builds in three different projects. Is this the previous version of rush?

**Comment by ShreyashSaitwal** [comment]
Awesome, it means the issue is now fixed!

> Is this the previous version of rush?

Nope. Its a different version.

**Comment by XomaDev** [comment]
Oh nice, yes its fixzeddd! building done:

```
user@DESKTOP-BD6HS68 MINGW64 ~/Desktop/Codes/parmesh/background-tasks
$ rush build
                      __
     _______  _______/ /_
    / ___/ / / / ___/ __ \
   / /  / /_/ (__  / / / /
  /_/   \__,_/____/_/ /_/

• Build initialized

┌ Checking project files
│
│  OK Metadata file (rush.yml) found
│
│  OK AndroidManifest.xml file found
└ Done
┌ Compiling Java files
└ Done
┌ Processing the extension
└ Done
┌ Converting Java bytecode to DEX bytecode
└ Done
┌ Finalizing the build
└ Done

• Build successful

user@DESKTOP-BD6HS68 MINGW64 ~/Desktop/Codes/parmesh/background-tasks
$

```

**Comment by XomaDev** [comment]
Thanks.
