### ISSUE TITLE
Dependency Sync Failed Rush 2.0

### ISSUE THREAD

**Issue by bigraymasoom** [shreyashsaitwal/rush-cli#62]
This is the verbose of rush deps sync

```
info  Downloading resolved artifacts...                                       
│ error Exception: Invalid artifact coordinate format: android-33.jar
Expected format: <groupId>:<artifactId>:<version>:<classifier?>
│ debug #0      new ArtifactMetadata (package:rush_cli/src/resolver/resolver.dart:23)
#1      ArtifactResolver.resolveArtifact (package:rush_cli/src/resolver/resolver.dart:321)
#2      SyncSubCommand.sync (package:rush_cli/src/commands/deps/sync.dart:312)
#3      SyncSubCommand.run (package:rush_cli/src/commands/deps/sync.dart:128)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:212)
<asynchronous suspension>
#5      main (file:///Users/muhammadhusnain/rush-cli/bin/rush.dart:11)
<asynchronous suspension>
```

**Comment by jewelshkjony** [comment]
You could show us your rush.yml.
**NOTE:** You can't download android.jar as dependency.

**Comment by bigraymasoom** [comment]
This error occurs even when there are no dependencies.

**Comment by shreyashsaitwal** [comment]
v2 is unreleased, please don't use it.
