### ISSUE TITLE
Build Failed each time on 2.0

### ISSUE THREAD

**Issue by bigraymasoom** [shreyashsaitwal/rush-cli#63]
System: Macos on Intel MacBook Pro 
Install:Built from sources
Error 

```
Muhammads-MacBook-Pro:testyou muhammadhusnain$ rush build -v
                    __
   _______  _______/ /_
  / ___/ / / / ___/ __ \
 / /  / /_/ (__  / / / /
/_/   \__,_/____/_/ /_/

- Initializing build ✓    ... (0.01s)
┌ Compiling sources
│ debug No manifests found in dependencies; skipping manifest merge             
│ info  Picked 1 source file                                                    
│ debug Bad state: No element                                                   
│ debug #0      ListBase.singleWhere (dart:collection/list.dart:167)
#1      ProcessRunner.runExecutable (package:rush_cli/src/utils/process_runner.dart:23)
<asynchronous suspension>
#2      Compiler.compileJavaFiles (package:rush_cli/src/commands/build/tools/compiler.dart:110)
<asynchronous suspension>
#3      BuildCommand._compile (package:rush_cli/src/commands/build/build.dart:249)
<asynchronous suspension>
#4      BuildCommand.run (package:rush_cli/src/commands/build/build.dart:69)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212)
<asynchronous suspension>
#6      main (file:///Users/muhammadhusnain/rush-cli/bin/rush.dart:11)
<asynchronous suspension>
│ debug Bad state: No element                                                   
│ debug #0      ListBase.singleWhere (dart:collection/list.dart:167)
#1      ProcessRunner.runExecutable (package:rush_cli/src/utils/process_runner.dart:23)
<asynchronous suspension>
#2      Compiler.compileJavaFiles (package:rush_cli/src/commands/build/tools/compiler.dart:110)
<asynchronous suspension>
#3      BuildCommand._compile (package:rush_cli/src/commands/build/build.dart:249)
<asynchronous suspension>
#4      BuildCommand.run (package:rush_cli/src/commands/build/build.dart:69)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212)
<asynchronous suspension>
#6      main (file:///Users/muhammadhusnain/rush-cli/bin/rush.dart:11)
<asynchronous suspension>
└ ×    ... (0.01s)

• BUILD FAILED (took 0.01s)                                                    
Muhammads-MacBook-Pro:testyou muhammadhusnain$
```

**Comment by shreyashsaitwal** [comment]
v2 is unreleased, please don't use it.
